---

- name: Ensure OpenVPN is started
  service:
    name: "{{ openvpn_service }}"
    state: started
    enabled: true
  # Adding changed_when: false to disable "service" module from reporting "changed" status in docker environment when testing the role with molecule.
  # Somehow setting the "started" state is not idempotent as it should be according to Ansible documentation. Hence, doing a hack here.
  changed_when: false
